version: "3.9"

services:
  # -----------------
  # Databases
  # -----------------
  auth-db:
    image: postgres:15
    restart: always
    env_file:
      - ./services/auth/.env
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # -----------------
  # Auth service
  # -----------------
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    depends_on:
      - auth-db
    env_file:
      - ./services/auth/.env
    ports:
      - "8001:8000"
    # no volume override → keeps shared + service code inside image

  # -----------------
  # Postgen service
  # -----------------
  postgen-service:
    build:
      context: .
      dockerfile: Dockerfile.postgen
    depends_on:
      - mongo
    env_file:
      - ./services/postgen/.env
    ports:
      - "8003:8000"

  # -----------------
  # Scraper service
  # -----------------
  scraper-service:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper
    restart: always
    depends_on:
      - mongo
    env_file:
      - ./services/scraper/.env
    ports:
      - "8005:8000"
    volumes:
      - /ms-playwright
      - ./services/scraper/state.json:/app/state.json  # safe: single-file override

  # -----------------
  # API Gateway (Main)
  # -----------------
  main-service:
    build:
      context: .
      dockerfile: Dockerfile.main
    depends_on:
      - auth-service
      - postgen-service
      - scraper-service
    env_file:
      ./services/main/.env.docker   # use docker env
    ports:
      - "8000:8000"

volumes:
  auth_data:
  mongo_data:
